import Head from 'next/head';
import Footer from './Footer';
import Header from './Header';

export default function LayoutFooterNone({ title, children }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      {children}
    </>
  );
}
